### ISSUE TITLE
Changing the resolution in GLideN64 doesn't scale the emulator window

### ISSUE THREAD

**Issue by lordlouckster** [anonymous7002/m64p#1]

**Comment by Jj0YzL5nvJ** [comment]
https://github.com/gonetz/GLideN64/issues/2373#issuecomment-720742021
https://github.com/loganmc10/m64p/issues/93#issuecomment-730385908
https://github.com/loganmc10/GLideN64/commit/7700190c9787a7729db2c26ae74801e30e625f88
https://github.com/anonymous7002/sneed64/blob/ad37721347620e22d4e43104164ad8d66c813989/build.sh#L84-L86

**Comment by lordlouckster** [comment]
It can load GLideN64, and access the configuration, but if you change the resolution mid-game, the game scales, but the program window doesn't.

**Comment by RokkumanX** [comment]
That's really weird, but frankly I know nothing about GLideN64 to be able to help you with it.

I'm more of an angrylion-rdp-plus type of guy.

I realize this comment is probably 99.8% useless but I just wanted to say thank you once again @anonymous7002 for all of this, it's so great finally having a Mupen64Plus frontend that makes you choose plugins instead of making Frankenstein builds.

To bad RMG went away so fast, damn that project had potential.

**Comment by lordlouckster** [comment]
It seems that this bug has existed in m64p already. I tested it, but I don't know if it's about the config file...
